import { CardModel } from "./interfaces/CardModel";

//raw data
export const cardsList: CardModel[] = [
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
  {
    name: "James Hiddleston",
    first_name: "James",
    last_name: "Hiddleston",
    current_title: "Machine Learning Engineer",
    location: "San Francisco Bay Area",
    phone_number: "1234567890",
    personal_email: "temp@gmail.com",
    linkedIn: "linkedin",
    experience: [
      "Senior Machine Learning Engineer at Google October - 2018 to February - 2020",
      "Junior Machine Learning Engineer at spotify June 2017 to August 2018",
    ],
    education: ["Stanford University, M.S., Computer Science October-2014 to May - 2017"],
  },
];
